# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.

# arknights-endfield-bp-tool
# 

# --- 第一阶段：构建 (Build Stage) ---
FROM node:20-slim AS build-stage

# 设置工作目录
WORKDIR /app

# 复制依赖定义
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制所有源代码
COPY . .

# 执行构建（这会运行 tsc 检查并生成 dist 目录）
RUN npm run build

# --- 第二阶段：托管 (Production Stage) ---
FROM nginx:stable-alpine

# 从构建阶段拷贝生成的静态文件到 Nginx 默认目录
# Vite 默认的输出目录是 dist
COPY --from=build-stage /app/dist /usr/share/nginx/html

# 暴露 80 端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]
